// const element = document.getElementById('selectMe')
// const element = document.getElementsByClassName('heading')
// const element = document.getElementsByTagName('div')
const element = document.querySelectorAll('.heading')
console.log(element)
